'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import type { Customer, DayOfWeek } from '@/types/database'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { StepBuilder, Step } from '@/components/employer/StepBuilder'

export default function NewJobPage() {
  const router = useRouter()
  const supabase = createClient()

  const [loading, setLoading] = useState(false)
  const [customers, setCustomers] = useState<Customer[]>([])
  const [employerId, setEmployerId] = useState<string>('')
  const [steps, setSteps] = useState<Step[]>([])

  // Form state
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    client_code: '',
    address: '',
    duration_minutes: '',
    price_per_hour: '',
    customer_id: '',
    timezone: 'America/Toronto',
    is_recurring: false,
    frequency_per_week: '',
    available_days: [] as string[],
    time_window_start: '',
    time_window_end: '',
    notes: '',
  })

  const DAYS_OF_WEEK = [
    { value: 'MON', label: 'Mon' },
    { value: 'TUE', label: 'Tue' },
    { value: 'WED', label: 'Wed' },
    { value: 'THU', label: 'Thu' },
    { value: 'FRI', label: 'Fri' },
    { value: 'SAT', label: 'Sat' },
    { value: 'SUN', label: 'Sun' },
  ]

  const toggleDay = (day: string) => {
    setFormData(prev => ({
      ...prev,
      available_days: prev.available_days.includes(day)
        ? prev.available_days.filter(d => d !== day)
        : [...prev.available_days, day]
    }))
  }

  useEffect(() => {
    fetchInitialData()
  }, [])

  const fetchInitialData = async () => {
    try {
      // Get current user
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) {
        router.push('/login')
        return
      }

      // Get employer record
      const { data: employer } = await supabase
        .from('employers')
        .select('id')
        .eq('user_id', user.id)
        .single()

      if (!employer) {
        console.error('Employer record not found')
        return
      }

      setEmployerId(employer.id)

      // Fetch customers
      const { data: customersData } = await supabase
        .from('customers')
        .select('*')
        .eq('created_by', employer.id)
        .eq('status', 'ACTIVE')
        .order('full_name', { ascending: true })

      setCustomers(customersData || [])
    } catch (error) {
      console.error('Error fetching initial data:', error)
    }
  }

  const generateJobCode = async (clientCode: string) => {
    if (!clientCode || clientCode.length !== 3) return null

    // Find the next available template number for this client code
    const { data: existingJobs } = await supabase
      .from('job_templates')
      .select('template_number')
      .eq('client_code', clientCode.toUpperCase())
      .order('template_number', { ascending: false })
      .limit(1)

    let nextNumber = 1
    if (existingJobs && existingJobs.length > 0) {
      const lastNumber = parseInt(existingJobs[0].template_number)
      nextNumber = lastNumber + 1
    }

    const templateNumber = nextNumber.toString().padStart(2, '0')
    const versionLetter = 'A'
    const jobCode = `${clientCode.toUpperCase()}-${templateNumber}${versionLetter}`

    return {
      client_code: clientCode.toUpperCase(),
      template_number: templateNumber,
      version_letter: versionLetter,
      job_code: jobCode,
    }
  }

  const handleSubmit = async (status: 'DRAFT' | 'ACTIVE') => {
    try {
      setLoading(true)

      // Validate employer ID is set
      if (!employerId) {
        alert('Session error. Please refresh the page.')
        return
      }

      // Validate required fields
      if (!formData.title || !formData.client_code) {
        alert('Please fill in title and client code')
        return
      }

      if (formData.client_code.length !== 3) {
        alert('Client code must be exactly 3 letters')
        return
      }

      // Generate job code
      const codeData = await generateJobCode(formData.client_code)
      if (!codeData) {
        alert('Failed to generate job code')
        return
      }

      // Prepare job template data (job_code is generated by database)
      const jobTemplate = {
        client_code: codeData.client_code,
        template_number: codeData.template_number,
        version_letter: codeData.version_letter,
        title: formData.title,
        description: formData.description || null,
        address: formData.address || null,
        duration_minutes: formData.duration_minutes ? parseInt(formData.duration_minutes) : null,
        price_per_hour: formData.price_per_hour ? parseFloat(formData.price_per_hour) : null,
        customer_id: formData.customer_id || null,
        timezone: formData.timezone,
        available_days: formData.available_days as DayOfWeek[],
        time_window_start: formData.time_window_start || null,
        time_window_end: formData.time_window_end || null,
        is_recurring: formData.is_recurring,
        frequency_per_week: formData.frequency_per_week ? parseInt(formData.frequency_per_week) : null,
        status: status,
        created_by: employerId,
        notes: formData.notes || null,
      }

      // Insert job template
      const { data, error } = await supabase
        .from('job_templates')
        .insert(jobTemplate)
        .select()
        .single()

      if (error) throw error

      // Insert steps if any
      if (steps.length > 0 && data) {
        for (const step of steps) {
          // Insert job step
          const { data: stepData, error: stepError } = await supabase
            .from('job_steps')
            .insert({
              job_template_id: data.id,
              step_order: step.step_order,
              title: step.title,
              description: step.description || null,
              products_needed: step.products_needed || null,
            })
            .select()
            .single()

          if (stepError) {
            console.error('Error creating step:', stepError)
            continue
          }

          // Insert checklist items for this step
          if (step.checklist_items.length > 0 && stepData) {
            const checklistItems = step.checklist_items
              .filter(item => item.trim() !== '')
              .map((item, index) => ({
                job_step_id: stepData.id,
                item_text: item,
                item_order: index + 1,
              }))

            if (checklistItems.length > 0) {
              const { error: checklistError } = await supabase
                .from('job_step_checklist')
                .insert(checklistItems)

              if (checklistError) {
                console.error('Error creating checklist items:', checklistError)
              }
            }
          }

          // Insert images for this step
          if (step.images.length > 0 && stepData) {
            const stepImages = step.images.map((image, index) => ({
              job_step_id: stepData.id,
              image_url: image.url,
              caption: image.caption || null,
              image_order: index + 1,
            }))

            const { error: imagesError } = await supabase
              .from('job_step_images')
              .insert(stepImages)

            if (imagesError) {
              console.error('Error saving step images:', imagesError)
            }
          }
        }
      }

      // Redirect back to jobs page
      router.push('/employer/jobs')
    } catch (error: unknown) {
      console.error('Error creating job:', error)
      const errorMessage = error instanceof Error
        ? error.message
        : (error as { message?: string })?.message || JSON.stringify(error)
      alert(`Failed to create job template: ${errorMessage}`)
    } finally {
      setLoading(false)
    }
  }

  const handleCustomerChange = (customerId: string) => {
    setFormData({ ...formData, customer_id: customerId })

    // Auto-fill client code from customer
    const customer = customers.find(c => c.id === customerId)
    if (customer) {
      setFormData({
        ...formData,
        customer_id: customerId,
        client_code: customer.customer_code,
        address: customer.address || '',
      })
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 p-4 pb-20">
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            onClick={() => router.back()}
            disabled={loading}
          >
            Cancel
          </Button>
          <h1 className="text-2xl font-bold text-gray-900">Create New Job</h1>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Job Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Job Type Selection */}
            <div className="space-y-2">
              <Label>Job Type</Label>
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant={formData.customer_id === '' && formData.client_code === 'RND' ? 'default' : 'outline'}
                  onClick={() => setFormData({ ...formData, customer_id: '', client_code: 'RND', address: '' })}
                  className="flex-1"
                >
                  Random Job
                </Button>
                <Button
                  type="button"
                  variant={formData.customer_id !== '' || formData.client_code !== 'RND' ? 'default' : 'outline'}
                  onClick={() => setFormData({ ...formData, client_code: '' })}
                  className="flex-1"
                >
                  Customer Job
                </Button>
              </div>
              <p className="text-xs text-gray-500">
                Random jobs use code RND. Customer jobs link to a customer profile.
              </p>
            </div>

            {/* Customer Selector (shown only for Customer Jobs) */}
            {formData.client_code !== 'RND' && (
              <div className="space-y-2">
                <Label htmlFor="customer">Customer</Label>
                <Select
                  value={formData.customer_id}
                  onValueChange={handleCustomerChange}
                >
                  <SelectTrigger id="customer">
                    <SelectValue placeholder="Select a customer" />
                  </SelectTrigger>
                  <SelectContent>
                    {customers.map(customer => (
                      <SelectItem key={customer.id} value={customer.id}>
                        {customer.full_name} ({customer.customer_code})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <p className="text-xs text-gray-500">
                  Selecting a customer will auto-fill the client code and address
                </p>
              </div>
            )}

            {/* Title */}
            <div className="space-y-2">
              <Label htmlFor="title">Job Title *</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                placeholder="e.g., Kitchen Deep Clean"
                required
              />
            </div>

            {/* Client Code (hidden for Random Jobs) */}
            {formData.client_code !== 'RND' && (
              <div className="space-y-2">
                <Label htmlFor="client_code">Client Code *</Label>
                <Input
                  id="client_code"
                  value={formData.client_code}
                  onChange={(e) => setFormData({ ...formData, client_code: e.target.value.toUpperCase() })}
                  placeholder="ABC"
                  maxLength={3}
                  className="uppercase"
                  required
                />
                <p className="text-xs text-gray-500">
                  3-letter code that identifies the client (e.g., ABC)
                </p>
              </div>
            )}

            {/* Description */}
            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                placeholder="Describe the job..."
                rows={4}
              />
            </div>

            {/* Address */}
            <div className="space-y-2">
              <Label htmlFor="address">Address</Label>
              <Input
                id="address"
                value={formData.address}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                placeholder="123 Main St, City, Province"
              />
            </div>

            {/* Duration and Price */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="duration">Duration (minutes)</Label>
                <Input
                  id="duration"
                  type="number"
                  value={formData.duration_minutes}
                  onChange={(e) => setFormData({ ...formData, duration_minutes: e.target.value })}
                  placeholder="120"
                  min="0"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="price">Price per Hour ($)</Label>
                <Input
                  id="price"
                  type="number"
                  step="0.01"
                  value={formData.price_per_hour}
                  onChange={(e) => setFormData({ ...formData, price_per_hour: e.target.value })}
                  placeholder="25.00"
                  min="0"
                />
              </div>
            </div>

            {/* Notes */}
            <div className="space-y-2">
              <Label htmlFor="notes">Internal Notes</Label>
              <Textarea
                id="notes"
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                placeholder="Notes visible only to you (not shown to employees)..."
                rows={2}
              />
            </div>
          </CardContent>
        </Card>

        {/* Scheduling Card */}
        <Card>
          <CardHeader>
            <CardTitle>Scheduling</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Available Days */}
            <div className="space-y-2">
              <Label>Available Days</Label>
              <div className="flex flex-wrap gap-2">
                {DAYS_OF_WEEK.map(day => (
                  <Button
                    key={day.value}
                    type="button"
                    variant={formData.available_days.includes(day.value) ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => toggleDay(day.value)}
                    className="w-12"
                  >
                    {day.label}
                  </Button>
                ))}
              </div>
              <p className="text-xs text-gray-500">
                Select which days this job can be scheduled
              </p>
            </div>

            {/* Time Window */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="time_start">Earliest Start Time</Label>
                <Input
                  id="time_start"
                  type="time"
                  value={formData.time_window_start}
                  onChange={(e) => setFormData({ ...formData, time_window_start: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="time_end">Latest Start Time</Label>
                <Input
                  id="time_end"
                  type="time"
                  value={formData.time_window_end}
                  onChange={(e) => setFormData({ ...formData, time_window_end: e.target.value })}
                />
              </div>
            </div>

            {/* Recurring Toggle */}
            <div className="space-y-2">
              <div className="flex items-center gap-3">
                <Label htmlFor="recurring">Recurring Job</Label>
                <Button
                  type="button"
                  variant={formData.is_recurring ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setFormData({ ...formData, is_recurring: !formData.is_recurring })}
                >
                  {formData.is_recurring ? 'Yes' : 'No'}
                </Button>
              </div>
              <p className="text-xs text-gray-500">
                Recurring jobs repeat every week until changed
              </p>
            </div>

            {/* Frequency (shown only if recurring) */}
            {formData.is_recurring && (
              <div className="space-y-2">
                <Label htmlFor="frequency">Times per Week</Label>
                <Input
                  id="frequency"
                  type="number"
                  min="1"
                  max="7"
                  value={formData.frequency_per_week}
                  onChange={(e) => setFormData({ ...formData, frequency_per_week: e.target.value })}
                  placeholder="e.g., 3"
                />
                <p className="text-xs text-gray-500">
                  How many times per week this job should occur
                </p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Step-by-Step Instructions Card */}
        <Card>
          <CardHeader>
            <CardTitle>Instructions (Optional)</CardTitle>
          </CardHeader>
          <CardContent>
            <StepBuilder steps={steps} onChange={setSteps} />
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex gap-3">
          <Button
            variant="outline"
            onClick={() => handleSubmit('DRAFT')}
            disabled={loading}
            className="flex-1"
          >
            {loading ? 'Saving...' : 'Save as Draft'}
          </Button>
          <Button
            onClick={() => handleSubmit('ACTIVE')}
            disabled={loading}
            className="flex-1"
          >
            {loading ? 'Saving...' : 'Activate Job'}
          </Button>
        </div>

        <p className="text-xs text-gray-500 text-center">
          Draft jobs can be edited later. Active jobs appear in the employee marketplace.
        </p>
      </div>
    </div>
  )
}
